export const CREATE_PROPERTY = "CREATE_PROPERTY";
export const LOAD_PROPERTIES_SUCCESS = "LOAD_PROPERTIES_SUCCESS";

export const CREATE_USER = "CREATE_USER";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";