export const CREATE_PROPERTY_SUCCESS = "CREATE_PROPERTY_SUCCESS";
export const UPDATE_PROPERTY_SUCCESS = "UPDATE_PROPERTY_SUCCESS";
export const DELETE_PROPERTY_OPTIMISTIC = "DELETE_PROPERTY_OPTIMISTIC";
export const LOAD_PROPERTIES_SUCCESS = "LOAD_PROPERTIES_SUCCESS";

export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";

export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";